package sneakbytes;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;


public class BuyAndSell extends javax.swing.JInternalFrame {

    /**
     * Creates new form loginFrame
     */
    public BuyAndSell() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SNEAK BYTES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        table.setBackground(new java.awt.Color(242, 242, 242));
        table.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Size", "Color", "Quantity", "Price", "Total"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Item");

        item.setActionCommand("<Not Set>");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });

        jLabel2.setText("Price");

        jLabel3.setText("Size");

        jLabel4.setText("Color");

        jLabel5.setText("Quantity");

        addButton.setBackground(new java.awt.Color(242, 242, 242));
        addButton.setText("Add Item");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(242, 242, 242));
        deleteButton.setText("Remove Item");
        deleteButton.setPreferredSize(new java.awt.Dimension(72, 23));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(242, 242, 242));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(242, 242, 242));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SNEAKBYTES");

        buyButton.setBackground(new java.awt.Color(242, 242, 242));
        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        sellButton.setBackground(new java.awt.Color(242, 242, 242));
        sellButton.setText("Sell");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(242, 242, 242));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(item, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(size, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(color, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(quantity, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(updateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(ClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Size", " Color", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void loadTableData(){
        try {
    String filePath = "src/main/java/sneakbytes/buy.txt";
    File file = new File(filePath);
    Scanner scan = new Scanner(file);
    DefaultTableModel tM = (DefaultTableModel) jTable1.getModel();

    while (scan.hasNext()) {
        String input = scan.nextLine();
        String separate[] = input.split(" ");
        String toInput[] = { separate[0], separate[1], separate[2], separate[3], separate[4] };

        boolean found = false;

        for (int row = 0; row < tM.getRowCount(); row++) {
            if (toInput[0].equals(tM.getValueAt(row, 0)) &&
                    toInput[1].equals(tM.getValueAt(row, 1)) &&
                    toInput[2].equals(tM.getValueAt(row, 2)) &&
                    toInput[4].equals(tM.getValueAt(row, 4))) {

                int currentQuantity = Integer.parseInt(tM.getValueAt(row, 3).toString());
                int stringValue = Integer.parseInt(separate[3]);
                int summation = currentQuantity + stringValue;

                tM.setValueAt(summation, row, 3);
                found = true;
                break; // Stop further searching as the item is found
            }
            
        }

        if (!found) {
            tM.addRow(toInput); // Add a new row if the item is not found
        }
        for (int row = 0; row < tM.getRowCount(); row++) {
        if(Integer.parseInt(tM.getValueAt(row, 3).toString()) <= 0){
                    tM.removeRow(row); 
            }
        }
    }
    
} catch (IOException e) {
    Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, e);
}
    }
    
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        //instantiate the table
        DefaultTableModel tM = (DefaultTableModel) table.getModel();
        //check if user only selected 1 row
        if(table.getSelectedRowCount() == 1){
            // initialize variables
            String itm = item.getText();
            String sz = size.getText();
            String clr = color.getText();
            String qtnty = quantity.getText();
            String prc = price.getText();
            int ttl = Integer.parseInt(qtnty)*Integer.parseInt(prc);
            //sets the table value
            tM.setValueAt(itm, table.getSelectedRow(), 0);
            tM.setValueAt(sz, table.getSelectedRow(), 1);
            tM.setValueAt(clr, table.getSelectedRow(), 2);
            tM.setValueAt(qtnty, table.getSelectedRow(), 3);
            tM.setValueAt(prc, table.getSelectedRow(), 4);
            tM.setValueAt(ttl, table.getSelectedRow(), 5);
            //clear the text fields
            item.setText("");
            price.setText("");
            size.setText("");
            color.setText("");
            quantity.setText("");
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        //instantiate the table
        DefaultTableModel tM = (DefaultTableModel) table.getModel();
        //if selected row is 1 proceed delete
        if(table.getSelectedRowCount() == 1){
            //delete row
            tM.removeRow(table.getSelectedRow());
            //clear the text fields
            item.setText("");
            price.setText("");
            size.setText("");
            color.setText("");
            quantity.setText("");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        // set text to total
        String Total = "";
        if(price.getText().equals("") || quantity.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill price and quantity data!");
        }else{
            int prc = Integer.parseInt(price.getText());
            int qnty = Integer.parseInt(quantity.getText());
            Total = Integer.toString(prc * qnty);
        }
        // check if text fields are empty
        if(item.getText().equals("")||price.getText().equals("")||size.getText().equals("")||color.getText().equals("")||quantity.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill all data!");
        }else if(Integer.parseInt(quantity.getText()) > 0){
            //strong all value to a string array
            String data[] = {item.getText(),size.getText(),color.getText(),quantity.getText(),price.getText(), Total};
            //instantiate the table
            DefaultTableModel tM = (DefaultTableModel) table.getModel();
            //add the array values to the table
            tM.addRow(data);
            //clear the text fields
            item.setText("");
            price.setText("");
            size.setText("");
            color.setText("");
            quantity.setText("");
        }else if(Integer.parseInt(quantity.getText()) <= 0){
        JOptionPane.showMessageDialog(this, "Invalid quantity input!");
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        //instantiate the table
        DefaultTableModel tM = (DefaultTableModel) table.getModel();
        // initialize variables
        String itm = tM.getValueAt(table.getSelectedRow(), 0).toString();
        String sz = tM.getValueAt(table.getSelectedRow(), 1).toString();
        String clr = tM.getValueAt(table.getSelectedRow(), 2).toString();
        String qtnty = tM.getValueAt(table.getSelectedRow(), 3).toString();
        String prc = tM.getValueAt(table.getSelectedRow(), 4).toString();
        //sets the text
        item.setText(itm);
        size.setText(sz);
        color.setText(clr);
        quantity.setText(qtnty);
        price.setText(prc);
    }//GEN-LAST:event_tableMouseClicked

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        //instantiate the table
        DefaultTableModel tM = (DefaultTableModel) table.getModel();
         String logPath = "src/main/java/sneakbytes/logs.txt";
         String filePath = "src/main/java/sneakbytes/buy.txt";
        File file = new File(filePath);
        File logFile = new File(logPath);
        try {
            try (FileWriter fw = new FileWriter(file, true); 
                    BufferedWriter bf = new BufferedWriter(fw)) {
                
                for(int i = 0; i < tM.getRowCount(); i++){
                    for(int j = 0; j < tM.getColumnCount() - 1; j++){
                        if(j == 3){
                        bf.write("-" + tM.getValueAt(i, j).toString() + " ");
                        }
                        else{
                            bf.write(tM.getValueAt(i, j).toString() + " ");
                        }
                    }
                    bf.write("\n");
                }

                bf.close();
                fw.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(BuyAndSell.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
               FileWriter lw = new FileWriter(logFile, true);
            try (BufferedWriter bw = new BufferedWriter(lw)) {
                for(int i = 0; i < tM.getRowCount(); i++){
                 bw.write("Sell ");   
                    for(int j = 0; j < tM.getColumnCount() - 1; j++){
                        bw.write(tM.getValueAt(i, j).toString() + " ");
                    }
                    bw.write(LocalDate.now().toString() + " ");
                    bw.write("\n");
                }
                
                
                JOptionPane.showMessageDialog(this, "Sell transaction completed!");
                bw.close();
                lw.close();
            }
            
        } catch (IOException ex) {
            Logger.getLogger(BuyAndSell.class.getName()).log(Level.SEVERE, null, ex);
        }

        tM.setRowCount(0);
    }//GEN-LAST:event_sellButtonActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        //instantiate the table
        DefaultTableModel tM = (DefaultTableModel) table.getModel();
        String filePath = "src/main/java/sneakbytes/buy.txt";
        String logPath = "src/main/java/sneakbytes/logs.txt";
        File file = new File(filePath);
        File logFile = new File(logPath);
        try {
            try (FileWriter fw = new FileWriter(file, true); 
                    BufferedWriter bf = new BufferedWriter(fw)) {
                
                for(int i = 0; i < tM.getRowCount(); i++){
                    for(int j = 0; j < tM.getColumnCount() - 1; j++){
                        bf.write(tM.getValueAt(i, j).toString() + " ");
                    }
                    bf.write("\n");
                }

                bf.close();
                fw.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(BuyAndSell.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
               FileWriter lw = new FileWriter(logFile, true);
            try (BufferedWriter bw = new BufferedWriter(lw)) {
                for(int i = 0; i < tM.getRowCount(); i++){
                  bw.write("Buy ");  
                    for(int j = 0; j < tM.getColumnCount() - 1; j++){
                        bw.write(tM.getValueAt(i, j).toString() + " ");
                    }
                    bw.write(LocalDate.now().toString() + " ");
                    bw.write("\n");
                }

                JOptionPane.showMessageDialog(this, "Buy transaction completed!");
                bw.close();
                lw.close();
            }
            
        } catch (IOException ex) {
            Logger.getLogger(BuyAndSell.class.getName()).log(Level.SEVERE, null, ex);
        }

        tM.setRowCount(0);

        
       
    }//GEN-LAST:event_buyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
           //instantiate the table
        DefaultTableModel tM = (DefaultTableModel) jTable1.getModel();
        // initialize variables
        String itm = tM.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String sz = tM.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String clr = tM.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String prc = tM.getValueAt(jTable1.getSelectedRow(), 4).toString();
        //sets the text
        item.setText(itm);
        size.setText(sz);
        color.setText(clr);
        price.setText(prc);
    }//GEN-LAST:event_jTable1MouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        item.setText("");
        size.setText("");
        color.setText("");
        quantity.setText("");
        price.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

         
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton buyButton;
    private javax.swing.JTextField color;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton sellButton;
    private javax.swing.JTextField size;
    private javax.swing.JTable table;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables


    
}
